# ┌──────────────────────────────────────────┐
# │            Look and Feel                 │
# └──────────────────────────────────────────┘

default_border pixel 2
default_floating_border pixel 2
hide_edge_borders smart
smart_borders on
smart_gaps on
gaps inner 4
gaps outer 4
focus_follows_mouse yes
mouse_warping none
workspace_layout default
titlebar_border_thickness 0
titlebar_padding 0

for_window [shell="xwayland"] title_format "%title [XWayland]"
