# ┌──────────────────────────────────────────┐
# │          Default Applications            │
# │  Change these to update everywhere       │
# └──────────────────────────────────────────┘

set $mod Mod4
set $terminal kitty
set $browser firefox
set $fileManager thunar
set $imageViewer imv-dir
set $menu rofi -show drun -show-icons
