# ┌──────────────────────────────────────────┐
# │           Window & Workspace Rules       │
# └──────────────────────────────────────────┘

for_window [app_id="thunar" title="^(File Operation Progress|Confirm)"] floating enable, resize set 500 300, move position center
for_window [class="steam" title="^(Friends List|Steam Settings)"] floating enable
for_window [app_id="pavucontrol"] floating enable, resize set 800 500, move position center
for_window [class="org.pulseaudio.pavucontrol"] floating enable, resize set 800 500, move position center
for_window [app_id="eye-candy"] floating enable, resize set 900 600, move position center, opacity 0.85
for_window [class="Rofi"] floating enable, opacity 0.92
for_window [app_id="dev.hypros.wallpaper-manager"] floating enable, resize set 1400 850, move position center
for_window [app_id="com.saivert.pwvucontrol"] floating enable, resize set 720 540, move position center
for_window [app_id="pwvucontrol"] floating enable, resize set 720 540, move position center
for_window [class="steam_app_.*"] fullscreen enable, opacity 1.0
for_window [class="gamescope"] fullscreen enable, opacity 1.0
for_window [app_id="dev.hypros.settings"] floating enable, move position center, opacity 1.0
for_window [app_id="dev.hypros.launcher"] floating enable, move position center

# To pin workspaces to a specific output, run `swaymsg -t get_outputs`
# and add rules like:
#   workspace 1 output DP-3
