# Video output
vo=gpu-next
hwdec=auto-safe

# Window behavior
force-window=immediate
keep-open=yes
autofit-larger=90%x90%

# OSD
osd-font="Iosevka Nerd Font"
osd-font-size=28

# Audio
volume=80
volume-max=150

# Screenshots
screenshot-directory=~/Pictures/Screenshots
screenshot-format=png

