# hypr-os hyprlock config

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 6
    noise = 0.02
    contrast = 0.9
    brightness = 0.6
}

input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(83a598)
    inner_color = rgb(282828)
    font_color = rgb(ebdbb2)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, -120
    halign = center
    valign = center
    rounding = 10
}

label {
    monitor =
    text = $TIME12
    color = rgb(ebdbb2)
    font_size = 72
    font_family = Iosevka Nerd Font
    position = 0, 60
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:3600000] date +"%A, %B %d"
    color = rgb(928374)
    font_size = 18
    font_family = Iosevka Nerd Font
    position = 0, -30
    halign = center
    valign = center
}
