# ┌──────────────────────────────────────────┐
# │          Default Applications            │
# │  Change these to update everywhere       │
# └──────────────────────────────────────────┘

$terminal = kitty
$browser = firefox
$fileManager = thunar
$imageViewer = imv-dir
$menu = rofi -show drun -show-icons
