# ┌──────────────────────────────────────────┐
# │          hypr-os / hyprland.conf         │
# │      Main config -- sources modules      │
# └──────────────────────────────────────────┘

# Programs
$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun -show-icons
$browser = firefox

# Source modular configs
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/theme.conf
