# ┌──────────────────────────────────────────┐
# │          hypr-os / hyprland.conf         │
# │      Main config -- sources modules      │
# └──────────────────────────────────────────┘

# Source modular configs
source = ~/.config/hypr/defaults.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/theme.conf
