# Default theme (overwritten by theme.sh)
foreground                      #ebdbb2
background                      #282828
selection_foreground            #282828
selection_background            #83a598
cursor                          #ebdbb2
cursor_text_color               #282828
url_color                       #83a598
active_border_color             #83a598
inactive_border_color           #504945
active_tab_background           #3c3836
active_tab_foreground           #ebdbb2
inactive_tab_background         #282828
inactive_tab_foreground         #928374
tab_bar_background              #1d2021

color0                          #282828
color8                          #928374
color1                          #fb4934
color9                          #cc241d
color2                          #b8bb26
color10                         #98971a
color3                          #fabd2f
color11                         #d79921
color4                          #83a598
color12                         #458588
color5                          #d3869b
color13                         #b16286
color6                          #8ec07c
color14                         #689d6a
color7                          #ebdbb2
color15                         #fbf1c7
