# hypr-os kitty config
include current-theme.conf

font_family      Iosevka Nerd Font Mono
font_size        13
window_padding_width 8
tab_bar_style    powerline
confirm_os_window_close 0
background_opacity 0.9
